### ISSUE TITLE
DeepL Free API

### ISSUE THREAD

**Issue by hurgir** [sonsuzanime/Auto-Subtitle-Translate-by-Sonsuz-Anime#3]
Merhaba, deepl limitsiz api seçeneğini entegre edebilirseniz eklenti çok kullanışlı olur. https://github.com/OwO-Network/DeepLX bu ve benzeri Deeplx repoları var.

**Comment by osmansonsuz** [comment]
Yeni bir eklenti çıkartmak mı yoksa entegre etmek mi daha mantıklı sizce ? Şu sıralar çalışıyorum işlerim yoğun ne zaman müsait olurum bilmiyorum. Müsait olunca update edeceğim eklentiyi.

**Comment by hurgir** [comment]
Yeni bir eklentiye gerek yok, entegre etmek yeterli olur.

**Comment by osmansonsuz** [comment]
> Yeni bir eklentiye gerek yok, entegre etmek yeterli olur.

Fikir için teşekkür ederim. Bu fikri ücretli versiyona dönüştürmek istiyorum. Yeni bir eklenti çıkartıp buy me a coffee üzerinden api key satışı gerçekleştirmeyi mantıklı buldum. Tek seferlik 1 veya 2 dolarlık bir ücret karşılığında kullanıcıya özel api oluşturup kullanıcının bu api ile kullanabilmesini istiyorum.
