### ISSUE TITLE
Script Altyazıyı Seçemiyor

### ISSUE THREAD

**Issue by yangkoson** [sonsuzanime/Auto-Subtitle-Translate-by-Sonsuz-Anime#6]
Hiçbir altyazıyı seçemiyorum Sub ID Not found diyor. Nasıl çözebilirim?

<img width="684" alt="Ekran Resmi 2024-09-08 19 35 46" src="https://github.com/user-attachments/assets/88dab62b-cc7e-4131-8c45-8dc1f51148a3">

**Comment by osmansonsuz** [comment]
Not found hatası almışsın bu şu demek;

Opensubtitles eklentisinde senin diline çevrilebilecek herhangi bir altyazı bulunmamakta veya benim veritabanımda da seçtiğin dilin altyazısı bulunmamakta. Yani benim eklentimin sana altyazı verebilmesi için Opensubtitles eklentisinde minimum 1 adet altyazı bulunması gerekli. Bulunmadığı için not found hatası almışsın, yapılabilecek birşey yok bu konuda.

**Comment by yangkoson** [comment]
opensubtitles altyazı bulsa bile altyazı senkronu kayık olabiliyor, bunları nasıl çözebilirim?

**Comment by osmansonsuz** [comment]
> opensubtitles altyazı bulsa bile altyazı senkronu kayık olabiliyor, bunları nasıl çözebilirim?

Stremionun kendi senkron ayarı var. Altyazıyı seçtikten sonra ayarlanacak zaman yazıyor attığın fotoğrafta o kısımdan + - şeklinde altyazının senkronunu yapabilirsin. Onun haricinde yapabileceğin bir şey bulunmamakta.
